# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        MainWindow.setStyleSheet("background-color: #32303b")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 757, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BoardBox = QtWidgets.QVBoxLayout()
        self.BoardBox.setObjectName("BoardBox")
        self.TurnBox = QtWidgets.QHBoxLayout()
        self.TurnBox.setContentsMargins(250, -1, 250, -1)
        self.TurnBox.setObjectName("TurnBox")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(40, 30))
        self.label.setMaximumSize(QtCore.QSize(50, 30))
        self.label.setObjectName("label")
        self.TurnBox.addWidget(self.label)
        self.Turn = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Turn.setMinimumSize(QtCore.QSize(30, 30))
        self.Turn.setMaximumSize(QtCore.QSize(30, 30))
        self.Turn.setText("")
        self.Turn.setObjectName("Turn")
        self.TurnBox.addWidget(self.Turn)
        self.line = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.line.setStyleSheet("background-color: #fff")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.TurnBox.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName("label_2")
        self.TurnBox.addWidget(self.label_2)
        self.Bot = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Bot.setMinimumSize(QtCore.QSize(30, 30))
        self.Bot.setMaximumSize(QtCore.QSize(30, 30))
        self.Bot.setText("")
        self.Bot.setObjectName("Bot")
        self.TurnBox.addWidget(self.Bot)
        self.BoardBox.addLayout(self.TurnBox)
        self.Board = QtWidgets.QGridLayout()
        self.Board.setSpacing(0)
        self.Board.setObjectName("Board")
        self.BoardBox.addLayout(self.Board)
        self.horizontalLayout.addLayout(self.BoardBox)
        self.history = QtWidgets.QVBoxLayout()
        self.history.setObjectName("history")
        self.horizontalLayout.addLayout(self.history)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "連珠"))
        self.label.setText(_translate("MainWindow", "Turn:"))
        self.label_2.setText(_translate("MainWindow", "Bot: "))


# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutPage(object):
    def setupUi(self, AboutPage):
        AboutPage.setObjectName("AboutPage")
        AboutPage.resize(672, 478)
        AboutPage.setStyleSheet("background-color: #32303b")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=AboutPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 4180, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setStyleSheet("font-size: 20px")
        self.label_4.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(650, 120))
        self.label.setScaledContents(False)
        self.label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("font-size: 20px")
        self.label_3.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(650, 16777215))
        self.label_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setStyleSheet("font-size: 10px")
        self.label_5.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)

        self.retranslateUi(AboutPage)
        QtCore.QMetaObject.connectSlotsByName(AboutPage)

    def retranslateUi(self, AboutPage):
        _translate = QtCore.QCoreApplication.translate
        AboutPage.setWindowTitle(_translate("AboutPage", "About"))
        self.label_4.setText(_translate("AboutPage", "Рэндзю"))
        self.label.setText(_translate("AboutPage",
                                      "Рэ́ндзю (яп. 連珠) — настольная логическая игра для двух игроков, спортивный вариант крестиков-ноликов до пяти в ряд, сочетающая в себе, кроме спортивных элементов, также элементы искусства и философии. Возникла в Китае более четырёх тысяч лет назад, вариации были известны и цивилизации инков, и Древнему Риму. В начале нашей эры игра из Китая попала в Японию, где и получила наибольшее распространение. Принятый спортивный вариант, равно как и название, также родились в Японии. Старые вариации игры известны также под названиями «гомоку» и «гомокунарабэ», что означает «пять камней» и «пять камней в ряд»."))
        self.label_3.setText(_translate("AboutPage", "Правила игры"))
        self.label_2.setText(_translate("AboutPage",
                                        "Играют два соперника: один чёрными фишками (камнями), другой — белыми. Игра проходит на расчерченной в клетку доске размером 15 на 15 линий.\n"
                                        "\n"
                                        "Игроки делают ходы по очереди. Первыми ходят чёрные. Каждым ходом игрок выставляет на доску в любое свободное пересечение линий доски один камень своего цвета. Побеждает тот, кто сможет первым построить непрерывный ряд из пяти камней своего цвета — по горизонтали, по вертикали или в диагональном направлении.\n"
                                        "\n"
                                        ""))
        self.label_5.setText(_translate("AboutPage", "материал взят: https://dzen.ru/a/ZD3ZqLn_KwCfPYW0"))


# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(344, 300)
        Settings.setMinimumSize(QtCore.QSize(344, 300))
        Settings.setMaximumSize(QtCore.QSize(344, 300))
        Settings.setStyleSheet("background-color: #32303b")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color: #373640")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 319, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.setting = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.setting.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.setting.setContentsMargins(0, 0, 0, 0)
        self.setting.setObjectName("setting")
        self.setting_name = QtWidgets.QLabel(parent=self.layoutWidget)
        self.setting_name.setMinimumSize(QtCore.QSize(150, 0))
        self.setting_name.setMaximumSize(QtCore.QSize(150, 30))
        self.setting_name.setStyleSheet("font-size: 20px")
        self.setting_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.setting_name.setObjectName("setting_name")
        self.setting.addWidget(self.setting_name, 0,
                               QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("background-color: #373640")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 319, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.setting2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.setting2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.setting2.setContentsMargins(0, 0, 0, 0)
        self.setting2.setObjectName("setting2")
        self.setting_name_2 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.setting_name_2.setMinimumSize(QtCore.QSize(150, 0))
        self.setting_name_2.setMaximumSize(QtCore.QSize(150, 30))
        self.setting_name_2.setStyleSheet("font-size: 20px")
        self.setting_name_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.setting_name_2.setObjectName("setting_name_2")
        self.setting2.addWidget(self.setting_name_2, 0,
                                QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.setting_name.setText(_translate("Settings", "Bot"))
        self.setting_name_2.setText(_translate("Settings", "BotV2"))
